#!/usr/bin/env bash
# install nginx & configures it on the server

apt-get update
apt-get -y install nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html

echo "Hello World!" > /etc/nginx/html/index.html

print %s "server {
  listen      80 default_server;
  listen      [::]:80 default_server;
  root        /etc/nginx/html;
  index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx start
