#!/usr/bin/env bash
# install nginx & configures it on the server
sudo apt-get -y update
sudo apt-get -y install nginx

sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
service nginx start
