#!/usr/bin/env bash
#the script to install nginx server

var_st_old="server_name _;"
var_st_new="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"

sudo apt-get -y update

sudo apt-get -y install nginx

sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i -e "s|$var_st_old|$var_st_new|" /etc/nginx/sites-enabled/default

sudo service nginx start
