#!/usr/bin/env bash
#create script to install and config haproxy on ib-01 server

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo sed -i -e "$aENABLED=1\n" /etc/default/haproxy
sudo sed -i -e "$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 258562-web-01 100.25.166.57:80 check\n\tserver 258562-web-02 54.173.193.255:80 check\n" /etc/haproxy/haproxy.cfg

sudo service haproxy restart
