#!/usr/bin/env bash
#create script to install and config haproxy on ib-01 server

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
