#!/usr/bin/env bash
#install and config haproxy

sudo apt-get -y update
sudo apt-get -y install haproxy

line="\nfrontend my_frontend\n\tbind *:80\n\tdefault_backend alx_backend\n\nbackend alx_backend\n\tbalance roundrobin\n\tserver 258562-web-01 100.25.166.57:80 check\n\tserver 258562-web-02 54.173.193.255:80 check"

sudo echo -e $line >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
