#!/usr/bin/env bash
#displays Best School 10 times, but for the 9th iteration

x=0

while [ $x -lt 10 ]
do
    if [ $x -eq 9 ]
    then
        echo  "Hi"
    fi
    echo "Best School"
    ((x++))
done
